# Generated by Django 6.0.4 on 2026-05-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student Intern'), ('workplace_supervisor', 'Workplace Supervisor'), ('academic_supervisor', 'Academic Supervisor'), ('admin', 'Internship Administrator'), ('supervisor', 'Supervisor (legacy)'), ('coordinator', 'Coordinator (legacy)')], default='student', max_length=20),
        ),
    ]
