# Generated by Django 5.2.6 on 2026-03-23 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='placements.internshipplacement'),
        ),
    ]
