# Generated by Django 5.2.6 on 2026-05-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_weeklylog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
