# Generated by Django 5.2.6 on 2026-06-10 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_remove_weeklylog_feedback_weeklylog_approved_by_and_more'),
        ('placements', '0004_alter_internshipplacement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_logs', to='placements.internshipplacement'),
        ),
    ]
